apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
  labels:
    app: opentelemetry-demo-adservice
spec:
  selector:
    app: opentelemetry-demo-adservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP