apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationdeployment
  labels:
    app: opentelemetry-demo-recommendationservice
    
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: opentelemetry-demo-recommendationservice
  template:
    metadata:
      labels:
        app: opentelemetry-demo-recommendationservice

    spec:
      serviceAccountName: opentelemetry-demo
      containers:
        - name: recommendationservice
          image: 'ghcr.io/open-telemetry/demo:1.12.0-recommendationservice'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: service
         
          
