---
# Source: opentelemetry-demo/templates/component.yaml
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  labels:
    app: opentelemetry-demo-recommendationservice
   
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: tcp-service
      targetPort: 8080
  selector:
    app: opentelemetry-demo-recommendationservice
